export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SETTINGS = 'LOAD_SETTINGS';

export const STREAM_DATA = 'STREAM_DATA';

export const LOAD_ALL_DATA = 'LOAD_ALL_DATA';
export const LOAD_TODAY_DATA = 'LOAD_TODAY_DATA';
export const LOAD_3DAY_DATA = 'LOAD_3DAY_DATA';
export const LOAD_7DAY_DATA = 'LOAD_7DAY_DATA';
export const LOAD_MONTH_DATA = 'LOAD_MONTH_DATA';
